### ISSUE TITLE
UID & GID mismatches between volume owner and container user

### ISSUE THREAD

**Issue by moretrim** [JJ/docker-raku-test#4]
The move away from running everything as root has broken a couple things on my end. On the one hand that’s understandable & not entirely unexpected, on the other hand I am unsure how to move on from here.

I have managed to condense my issues to the following mock `.travis.yml` snippet:

```yml
os:
  - linux

language:
  - minimal

services:
  - docker

before_install:
  - docker pull jjmerelo/raku-test

matrix:
  include:
    - name: "Debug me!"
      script: |
        docker run -t \
          --name container-env \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint /bin/sh \
          jjmerelo/raku-test -c '
            id
            ls -la /
            ls -la ~
            ls -la /test
            mkdir something-or-other
            ls -la something-or-other
          '
```

(Quickly frankensteined from the bits and pieces I have on my end, hopefully I got it right.)

The output from running the job (with long output from `ls` abridged):

```
$ docker run -t \
  --name container-env \
  --volume "$TRAVIS_BUILD_DIR":/test \
  --entrypoint /bin/sh \
  jjmerelo/raku-test -c '
    id
    ls -la /
    ls -la ~
    ls -la /test
    mkdir something-or-other
    ls -la something-or-other
  '

uid=100(raku) gid=101(raku) groups=101(raku)
total 68
drwxr-xr-x    1 root     root          4096 Aug 20 02:03 .
drwxr-xr-x    1 root     root          4096 Aug 20 02:03 ..
-rwxr-xr-x    1 root     root             0 Aug 20 02:03 .dockerenv
…snip…
total 16
drwxr-sr-x    1 raku     raku          4096 Aug  3 10:52 .
drwxr-xr-x    1 root     root          4096 Aug  3 10:34 ..
drwxr-sr-x    8 raku     raku          4096 Aug  3 10:46 .raku
drwxr-sr-x    4 raku     raku          4096 Aug  3 10:49 .zef
total 48
drwxrwxr-x    4 2000     2000          4096 Aug 20 02:02 .
drwxr-xr-x    1 root     root          4096 Aug 20 02:03 ..
drwxrwxr-x    8 2000     2000          4096 Aug 20 02:02 .git
…snip…
mkdir: can't create directory 'something-or-other': Permission denied
ls: something-or-other: No such file or directory
```

Child image `jjmerelo/raku-test` is running the container as `raku` with UID 100 while the volume on `/test` is owned by 2000. From my limited understanding of Docker things, perhaps the owner of `/test` is the remapped `raku` from base image `jjmerelo/alpine-raku`? (Likewise groups and GIDs.)

In any case the inability to write to the volume is what breaks things on my end.
